### ISSUE TITLE
Create shell 'state-evaluator' AI

### ISSUE THREAD

**Issue by olyis** [markbutler94/risk#9]
The minimum necessary to get this AI rolling.

This component should be the actual AI script that the game calls.
State evaluator can be a stub for now, and this shell can just implement the attackTerritory call.

**Comment by olyis** [comment]
Plan is to make a shell which works out all possible attacks, given the state. Then for each possible attack, weighted by probability distribution over win/loss count, work out the resulting state and send it to the black box evaluator. Pick the attack with the best expected value! Also evaluate the _current_ state (no attacks). If it's better than all the others, stop attacking.

**Comment by olyis** [comment]
Every other call just goes through to the ai_basic version of the action.
Once we've got this first evaluator-based action in place, it's probably enough to have a go at training it and see how it does :D

**Comment by markbutler94** [comment]
Presumably we need some sort of metric on the states - we won’t have data
for all possible states (to even store this much data would be infeasible
no?) so the algorithm should (if it doesn’t find the exact state) choose
the closest, or some kind of weighted average of the n closest?

**Comment by olyis** [comment]
Yep, 100% no way for it to be a lookup! There are infinitely many possible states, I think?! But this is where we get to be creative. First try could be completely hand-coded; later attempts could use machine learning to try to improve it. It actually doesn't need to be a super-accurate function from state to win-probability (although that would be ideal) - just has to give bigger values for better states as often as possible. And definitely give low values for bad states!

**Comment by olyis** [comment]
For this issue, I'm planning to have the hackiest/most dreadful evaluator that just returns something like 1/(number of players left). But then we could try out hand coding some basics in, or just go straight to collecting data and training something up.

**Comment by markbutler94** [comment]
A thought I had today: the tactics one uses in RISK are (possibly) more dependent on local data than on global data. 

Suppose we have two game states: one where the player owns all of South America (and nothing else), and one where they own all of Africa (and nothing else). Any global state-evaluator, capable of providing useful information about where to attack next, must surely include (as a minimum) global territory ownership. (Here’s where I can’t see how it could work without a metric on the states — even if the initial number of players is limited, to four say, there are over 8e23 ways this could happen, and that’s just when all four players are still in! Even if you consider all enemy players as just one, it’s still in the hundreds of millions.) But any naive metric on this data would give 0% similarity between these cases, despite the desired tactics probably being similar.

So how about using local data instead? Possibly consider subgraphs of radius *n* (I think *n*=2 may work) from a given point. There are only 42 of these (and some are isomorphic, so could potentially (?) be considered equal — if we forget temporarily about global factors such as continent bonuses etc.), and by inspection none have more than about 15 vertices on the standard map. There are still a lot of possibilities (and that’s if we only look at ownership, not strength, which is probably not enough), but it reduces the problem significantly; possibly to the point that a metric on this local data could be really meaningful?

Let me know if I’m completely on the wrong track here!
